syntax = "proto3";

package core.payment.v1;

enum PaymentGatewayType {
  PAYMENT_GATEWAY_TYPE_UNSPECIFIED = 0;
  PAYMENT_GATEWAY_TYPE_POLAR = 1;
}

// PaymentStatusType는 결제 상태를 관리하기 위한 enum 이다.
enum PaymentStatusType {
  PAYMENT_STATUS_TYPE_UNSPECIFIED = 0;
  // 결제 처리중
  PAYMENT_STATUS_TYPE_PENDING = 1;
  // 결제 성공
  PAYMENT_STATUS_TYPE_SUCCEEDED = 2;
  // 결제 실패
  PAYMENT_STATUS_TYPE_FAILED = 3;
  // 환불
  PAYMENT_STATUS_TYPE_REFUNDED = 4;
  // 결제 취소
  PAYMENT_STATUS_TYPE_CANCELED = 5;
}

// PG 정보
message PaymentGatewayInfo {
  string account_id = 1;
  // PG사 정보
  PaymentGatewayType type = 2;
  // 해당 플랫폼에서 할당된 결제 id
  // POLAR 같은 포인트 관리가 탑재된 서비스의 경우 필요함
  string external_id = 3;
  // 결제 우선 순위
  uint32 priority = 4;
}
