syntax = "proto3";

package core.auth.v1;

import "buf/validate/validate.proto";
import "core/auth/v1/auth_model.proto";

service AccountService {
  // 서비스별 계정 상태 조회
  rpc GetAccountInfoByService(GetAccountInfoByServiceRequest) returns (GetAccountInfoByServiceResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
}

message GetAccountInfoByServiceRequest {
  // 대상 서비스명칭을 넣는다.
  //
  // [ port, craft, shop ]
  string service_name = 1 [(buf.validate.field).string = {
    in: [
      "PORT",
      "CRAFT",
      "SHOP"
    ]
  }];
}

message GetAccountInfoByServiceResponse {
  // 만약 status가 ACCOUNT_STATUS_BY_SERVICE_TYPE_OK 가 아닌경우 해당 서비스 전용 가입 로직을 타게 한다.
  AccountStatusByServiceType status = 1;

  // 계정 정보
  AccountInfo account_info = 2;
}
