syntax = "proto3";

package post.v1;

import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option go_package = "post/v1";

service CommentService {
  // 포스트에 대한 댓글 리스트 조회
  // parent_id 를 통해 대댓글 조회도 가능
  rpc GetCommentList(GetCommentListRequest) returns (GetCommentListResponse);
  // 댓글 id 기반 조회
  rpc GetCommentInfo(GetCommentInfoRequest) returns (GetCommentInfoResponse);
}

service PostService {
  // post 정보 가져오기. -> 영상링크, 제목, 게시자, 좋아요, 조히수, 게시 시간, 썸네일 주소, description,
  // post 조회
  rpc GetPost(GetPostRequest) returns (GetPostResponse);
  rpc GetPostList(GetPostListRequest) returns (GetPostListResponse);
  rpc UpdateViewCount(UpdateViewCountRequest) returns (google.protobuf.Empty);
}

service StudioService {
  rpc GetStudioInfo(GetStudioInfoRequest) returns (GetStudioInfoResponse);
  //  rpc GetSubscriberInfo(GetSubscriberInfoRequest) returns (GetSubscriberInfoResponse);
  rpc GetSubscribedInfo(GetSubscribedInfoRequest) returns (GetSubscribedInfoResponse);
  rpc SetSubscribe(SetSubscribeRequest) returns (google.protobuf.Empty);
}

// 공통 사용 속성
message ContentFile {
  string url = 1;
  int32 position = 2;
}
message Post {
  string post_id = 1;
  string studio_id = 2;
  string type = 3;
  string title = 4;
  bool is_published = 5;
  string description = 6;
  int64 comment_count = 7;
  int64 like_count = 8;
  int64 un_count = 9;
  int64 view_count = 10;
  // 영상일 경우 재생 시간
  google.protobuf.Duration duration = 11;

  repeated ContentFile content_list = 12;

  google.protobuf.Timestamp created_at = 21;
  google.protobuf.Timestamp updated_at = 22;
  google.protobuf.Timestamp deleted_at = 23;
}

message Comment {
  string comment_id = 1;
  string studio_id = 2;
  string parent_comment_id = 3;
  string text = 4;
  string status = 5;
  bool is_pinned = 6;
  int32 depth = 7;
  int64 like_count = 8;
  int64 unlike_count = 9;

  string studio_name = 10;

  google.protobuf.Timestamp created_at = 20;
  google.protobuf.Timestamp updated_at = 21;
  google.protobuf.Timestamp deleted_at = 22;

  // 관리용
  string user_id = 30;
}
message GetPostRequest {
  string post_id = 1; // 요청 영상 id
}

message GetPostResponse {
  Post post = 1;
}

message GetCommentListRequest {
  string post_id = 1; // 게시된 그것의 아이디
  string parent_id = 2; // 대댓글의 경우 상위 댓글 id
}

message GetCommentListResponse {
  repeated Comment comment_list = 1;
}

message GetCommentInfoRequest {
  string comment_id = 1; // 댓글 id
}

message GetCommentInfoResponse {
  Comment comment = 1;
}

message GetPostListRequest {
  // 해당 studio_id 일 경우 해당 스튜디오에서 만든 영상만 뜬다.
  string studio_id = 1;
  // 현재 영상 기준 추천 영상들 표시
  string current_post_id = 2;
  // 검색
  SearchQuery query = 3;

  // 무한 스크롤 정보
  InfinityScrollParam infinity_scroll_param = 4;
}
enum SearchType {
  SEARCH_TYPE_UNSPECIFIED = 0; // 전체
  SEARCH_TYPE_STUDIO = 1;
  SEARCH_TYPE_VIDEO = 2;
  SEARCH_TYPE_VERTICAL_VIDEO = 3;
  SEARCH_TYPE_IMAGE = 4;
  SEARCH_TYPE_TEXT = 5;
  SEARCH_TYPE_AUDIO = 6;
  SEARCH_TYPE_PLAYLIST = 7;
  SEARCH_TYPE_COMMUNITY = 8; // 게시판
}

enum SearchOrderType {
  SEARCH_ORDER_TYPE_UNSPECIFIED = 0; // 관련성
  SEARCH_ORDER_TYPE_POPULARITY_DESC = 1; // 인기도 내림차순
  SEARCH_ORDER_TYPE_VIEW_COUNT_DESC = 2; // 조회수 내림차순

  SEARCH_ORDER_TYPE_POPULARITY_ASC = 11; // 인기도 오름차순
  SEARCH_ORDER_TYPE_VIEW_COUNT_ASC = 12; // 조회수 오름차순
}

message SearchQuery {
  // 검색 키워드
  string keyword = 1;
  // 검색시 태그
  repeated string tags = 2;
  SearchType type = 3;
  SearchOrderType order_by = 4;

  // 검색 날짜 조건
  google.protobuf.Timestamp before_at = 10;
  google.protobuf.Timestamp after_at = 11;
}

message InfinityScrollParam {
  // 현재 조회된 요소의 마지막 아이템 id
  // sql 조회시 해당 id 다음 요소부터 조회됨
  string cursor = 1;
  // 조회 단위 갯수
  int32 size = 2;
}

message GetPostListResponse {
  repeated Post post_list = 1;
}
enum StudioTapType {
  STUDIO_TAP_TYPE_UNSPECIFIED = 0;
  STUDIO_TAP_TYPE_VIDEO = 1;
  STUDIO_TAP_TYPE_VERTICAL_VIDEO = 2;
  STUDIO_TAP_TYPE_IMAGE = 3;
  STUDIO_TAP_TYPE_TEXT = 4;
  STUDIO_TAP_TYPE_AUDIO = 5;
  STUDIO_TAP_TYPE_PLAYLIST = 6;
  STUDIO_TAP_TYPE_COMMUNITY = 7; // 게시판
}

message StudioInfo {
  string studio_id = 1;
  string uid = 2;
  string name = 3;
  string description = 4;
  string region = 5;
  string email = 6;
  int64 sub_count = 7;
  int64 post_count = 8;

  string avatar_image = 9;
  string banner_image = 10;

  repeated StudioTapType tabs = 11;

  bool is_public = 20; // 소유자만 확인 가능
}
message GetStudioInfoRequest {
  string studio_id = 1;
}

message GetStudioInfoResponse {
  StudioInfo studio_info = 1;
}

message UpdateViewCountRequest {
  string post_id = 1;
  string studio_id = 2;
  string ip = 3;
  string user_agent = 4;
  string fingerprint = 5;
}

// 해당 요청에서 커서는 subscribe_at이 된다.
message GetSubscribedInfoRequest {
  InfinityScrollParam infinity_scroll_param = 1;
}

message GetSubscribedInfoResponse {
  repeated StudioInfo studio_list = 1;
}

message SetSubscribeRequest {
  string target_studio_id = 1;
}
